Change dictionnary workflow
Cruder/dictionary_C pull request #16
Opened 2016-11-26 21:53 UTC by alex-lairan

2016-11-27 12:04 UTC, amelie-certin submitted a review, later dismissed

2016-11-27 12:10 UTC, amelie-certin requested changes

2016-11-27 12:10 UTC, amelie-certin commented on src/gestbib.c
> +void menuOpenDictionary(void) {
Doc

2016-11-27 12:10 UTC, amelie-certin commented on src/gestbib.c
> +char *menuSelectDictionary(void) {
Doc

2016-11-30 18:53 UTC, TristanEduProjet submitted a review, later dismissed

2016-12-03 20:49 UTC, amelie-certin approved these changes

2016-12-03 20:50 UTC, merged