Suppression de la librairie md5.
Cruder/dictionary_C pull request #26
Opened 2016-12-10 14:41 UTC by TristanEduProjet

Suite à l'interdiction du prof d'utiliser une librairie externe.

2016-12-11 08:44 UTC, alex-lairan requested changes

2016-12-11 08:44 UTC, alex-lairan commented on lib/CMakeLists.txt
> +#add_subdirectory(folderlib)
Tu devrai retirer cette ligne.

Une pr doit être composée uniquement de ce qu'elle doit faire, je ne vois pas l’intérêt de ceci.

2016-12-11 08:44 UTC, alex-lairan commented on src/CMakeLists.txt
> +#Adding lib example
Tu devrai retirer cette ligne.

Une pr doit être composée uniquement de ce qu'elle doit faire, je ne vois pas l’intérêt de ceci.

2016-12-11 08:44 UTC, alex-lairan commented on src/CMakeLists.txt
> +#target_link_libraries(DictionaryX libname)
Tu devrai retirer cette ligne.

Une pr doit être composée uniquement de ce qu'elle doit faire, je ne vois pas l’intérêt de ceci.

2016-12-11 09:31 UTC, alex-lairan commented
On ca m'a l'air bon, si possible tu peux fixup (ou squash) tes commits stp?

2016-12-12 08:56 UTC, amelie-certin approved these changes

2016-12-12 09:02 UTC, alex-lairan commented
On ca m'a l'air bon, si possible tu peux fixup (ou squash) tes commits stp? (bis)

2016-12-12 09:16 UTC, TristanEduProjet commented
Le(s)quel(s) ?

2016-12-12 09:19 UTC, alex-lairan commented
Merge branch 'develop' into project/cancel_libmd5

2016-12-12 09:43 UTC, alex-lairan approved these changes

2016-12-12 09:43 UTC, merged