Ajout de la libraire de gestion de la console au projet.
Cruder/dictionary_C pull request #29
Opened 2016-12-10 20:54 UTC by TristanEduProjet

Ajout de la libraire au projet.

2016-12-10 21:58 UTC, alex-lairan requested changes

2016-12-10 21:58 UTC, alex-lairan commented on src/CMakeLists.txt
> +#target_link_libraries(DictionaryX AccelLib)
Pas d'interet

2016-12-10 21:58 UTC, alex-lairan commented on lib/AccelLib/include/AccelLib/terminal.h
> +typedef enum COULEUR_TERMINAL
Ta lib est en francais? :/

2016-12-10 22:31 UTC, TristanEduProjet commented on lib/AccelLib/include/AccelLib/terminal.h
> +typedef enum COULEUR_TERMINAL
Oui vu que je l'ai crée, elle est en français.

2016-12-10 22:32 UTC, TristanEduProjet commented on src/CMakeLists.txt
> +#target_link_libraries(DictionaryX AccelLib)
Je l'ai ajouter pour pouvoir l'utiliser dans la feature 19 en n'ayant juste qu'à la dé-commenter.

2016-12-10 22:33 UTC, alex-lairan commented on src/CMakeLists.txt
> +#target_link_libraries(DictionaryX AccelLib)
Donc par pour celle ci, ca ne sert à rien

2016-12-10 22:34 UTC, alex-lairan commented on lib/AccelLib/include/AccelLib/terminal.h
> +typedef enum COULEUR_TERMINAL
@amelie-certin vue que tu bosse sur les menu t'en pense quoi?

Moi j'en veux pas dans mon code metier perso.
Je refuserais tous code dans la partie métier en francais.

2016-12-11 08:49 UTC, alex-lairan commented
Tu as un code d'exemple?

2016-12-11 09:01 UTC, TristanEduProjet commented
Non, et vu comme les fonctions sont simple (car s'appuie sur les signatures des fonctions standards qu'elles reprennent), je n'ai pas pris le temps de le faire.
Après je vais commencer à l'utiliser dès que c'est validé, donc tu vas avoir des exemples assez rapidement.

2016-12-11 09:40 UTC, alex-lairan commented
D'accord, mais sans francais hein ..

2016-12-11 09:48 UTC, TristanEduProjet commented
bien sûr ;)

2016-12-11 10:41 UTC, alex-lairan approved these changes

2016-12-11 10:42 UTC, amelie-certin approved these changes

2016-12-11 10:42 UTC, merged