Feature/32/search unexists words
Cruder/dictionary_C pull request #34
Opened 2016-12-11 19:57 UTC by alex-lairan

2016-12-11 20:52 UTC, TristanEduProjet requested changes

2016-12-11 20:52 UTC, TristanEduProjet commented on src/gestorth.c
> +void listUnexistsWords(Dictionary *dictionary, const char *filename) {
Il manque la documentation.

2016-12-11 20:52 UTC, TristanEduProjet commented on src/gestorth.c
> +        if(wordPresent(dictionary, str) == false && strlen(str) > 0) {
Il faudrait inverser les 2 conditions pour que la longueur soit testée avant la recherche du mot (vide).

2016-12-11 20:52 UTC, TristanEduProjet commented on src/utils.c
> +    char clean[] = ".!?,;:/_";
il serait peut-être plus simple de faire avec `isalpha()` et `== '-'` ?

2016-12-11 21:47 UTC, alex-lairan commented on src/gestorth.c
> +        if(wordPresent(dictionary, str) == false && strlen(str) > 0) {
Non

2016-12-11 21:47 UTC, alex-lairan commented on src/gestorth.c
> +void listUnexistsWords(Dictionary *dictionary, const char *filename) {
:+1:

2016-12-11 21:47 UTC, alex-lairan commented on src/utils.c
> +    char clean[] = ".!?,;:/_";
Justement l'aventage est de pouvoir ajouter tous char que l'on veux virer

2016-12-11 22:36 UTC, amelie-certin requested changes

2016-12-11 22:36 UTC, amelie-certin commented on src/gestorth.c
> +    while(1) {
Non.

2016-12-12 08:52 UTC, amelie-certin requested changes

2016-12-12 08:52 UTC, amelie-certin commented on src/gestorth.c
> + * \param filename  The name of the file who contain the text
brief ?

2016-12-12 08:52 UTC, amelie-certin commented on src/utils.c
> + */
biref ?

2016-12-12 10:33 UTC, alex-lairan commented on src/gestorth.c
> + * \param filename  The name of the file who contain the text
Done

2016-12-12 11:11 UTC, amelie-certin requested changes

2016-12-12 11:11 UTC, amelie-certin commented on src/gestorth.c
> +    FILE *file = fopen(filename, "r");
Rajouter une securite dans le cas ou le fichier n'existe pas

2016-12-12 11:24 UTC, amelie-certin commented
Le dernier mot du fichier texte, s'il est absent du fichier dictionnaire, est affiché deux fois.

2016-12-12 13:34 UTC, alex-lairan commented on src/gestorth.c
> +    FILE *file = fopen(filename, "r");
done

2016-12-14 10:53 UTC, amelie-certin reviewed
Question

2016-12-14 10:53 UTC, amelie-certin commented on src/gestorth.c
> +            ++counter;
Variable inutilisée

2016-12-14 10:53 UTC, amelie-certin commented on src/gestorth.c
> +            }
A quoi sert cela ? str sera dans tous les cas soit free, soit réaffecté

2016-12-14 10:55 UTC, alex-lairan commented on src/gestorth.c
> +            }
Cela corrige le problème de mot qui ne se remplissent pas totalement.

2016-12-14 10:58 UTC, amelie-certin approved these changes

2016-12-14 12:45 UTC, alex-lairan commented
@TristanEduProjet can you review please?

2016-12-14 13:20 UTC, TristanEduProjet requested changes
Une question, sinon ok.

2016-12-14 13:20 UTC, TristanEduProjet commented on src/utils.c
> +    char clean[] = ".!?,;:/_";
peut-être rajouté `'&\"()[]{}=+*\\#|` ?
voir même `<>^¨~$£¤%§`

2016-12-14 13:26 UTC, amelie-certin commented on src/utils.c
> +    char clean[] = ".!?,;:/_";
Pour la simple quote c'est un peu tricky. En francais, une apostroche separe en general deux mots, mais pas toujours : `aujourd'hui`.

En anglais c'est pire, ca peut etre une marque du possessif : `Johnny's car`

2016-12-14 13:45 UTC, TristanEduProjet approved these changes

2016-12-14 13:45 UTC, merged